PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

MARGATROID_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
MARGATROID_BUILD_TYPE := $(RELEASE_TYPE)

ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(MARGATROID_BUILDTAG)),)
    MARGATROID_BUILDTAG := UNOFFICIAL
endif

MARGATROID_VERSION_SUFFIX := $(MARGATROID_BUILD_DATE)-$(MARGATROID_BUILDTAG)-$(MARGATROID_BUILD)

MARGATROID_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(MARGATROID_VERSION_SUFFIX)

MARGATROID_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(MARGATROID_VERSION_SUFFIX)
